### ISSUE TITLE
Keeps Switching to Password

### ISSUE THREAD

**Issue by jmocs94** [liquidx/webviewscreensaver#14]
Is anyone else having an issue with setting it to a url and then 5 seconds after screensaver starts it goes to the blurry screen and asks for their password to login? 

Basically it still displays the URL in the background but it is on the OS X Login Password Prompt as if I shook the mouse.

**Comment by dmalinovsky** [comment]
If I understand your issue properly I have similar one after upgrading to OS X 10.11 (El Capitan) public beta.  Even if I log in onto the website in Safari, the screensaver keeps displaying me the login page for the selected website.

**Comment by kladd** [comment]
I have the same issue jmocs94 is talking about. The OS X login screen, which blurs the background web view is somehow automatically triggered after a few seconds as though you've moved the mouse or pressed a key. Interestingly, [Octoscreen](https://github.com/orderedlist/octoscreen) which is also a web view does not have this problem. But when I switch the url to something else, the problem comes back. On OS X 10.10. I'll report back if I happen to learn anything.

**Comment by shawngiese** [comment]
I also have 10.11 and the password login keeps appearing after a few seconds.

**Comment by optimality** [comment]
I'm on 10.11.4, same problem as shawngiese.  After a few seconds the login screen pops up, blurs the background.

**Comment by medoix** [comment]
+1

**Comment by agologan** [comment]
Should not be a problem with latest `v2.1`.
