### ISSUE TITLE
Yosemite can't add new urls or change time

### ISSUE THREAD

**Issue by LekeFly** [liquidx/webviewscreensaver#24]
version: 10.10.5 (14F27), anyone seen this problem? Does it work in El Capitan?

**Comment by bettse** [comment]
I had a little trouble at first since I was trying to double or triple click the existing url to edit it.  What I found was that I needed to select a url in the list, such that it has a dark background, then click once and wait a beat and it turned into editable text.  

Its a lot like how Finder does it for renaming files:, if you double click, it opens the file, if you have the file selected and click (and release) and just wait a tick, it becomes editable.

**Comment by squidbits** [comment]
Right clicking the URL or time makes them editable for me.

**Comment by philgyford** [comment]
I nearly gave up on this because I thought the app was broken! It seemed like all I could do was add or remove www.google.com. It would be good if, at least, double-clicking on a URL made it editable, as it's not at all clear how to add URLs otherwise.

**Comment by droidomz** [comment]
omg thank you for this post, I was about to give up on it as well. One tip I can suggest is using Tab key multiple times instead of trying to find the magic spot for the mouse to be placed in the text field.

**Comment by evaame** [comment]
Another here who almost gave up (in fact I did for a whole week, but I'm stubborn and I found this thread, thank you all!). 

The app is wonderful, but there's lots of room for improvement in the UI. I can imagine many potential users are giving up because the interface is misleading and setting up is, at best, very frustrating.

**Comment by loadedsith** [comment]
I noticed this too, I have good luck using a "stuttered" 3 clicks: I imagine the first click focuses the area, and then double click on the form.

**Comment by agologan** [comment]
I had a blast reading this topic, as I've been bitten by this weird '90s interaction many times.

We may be changing this in a future version but for now I actually added a note in the (README)[https://github.com/liquidx/webviewscreensaver/blob/master/README.md]
