### ISSUE TITLE
Getting "Plugin Blocked" Error

### ISSUE THREAD

**Issue by gmmethekeys** [liquidx/webviewscreensaver#26]
I saw the reddit post https://www.reddit.com/r/space/comments/49yjf1/use_the_iss_earth_live_feed_as_your_screen_saver/ today and I am trying to set my monitors up to stream the ISS feed of earth. I'm getting the plugin blocked error when it tries to display the primary feed (http://www.ustream.tv/embed/17074538?v=3&amp;controls=false&autoplay=true).

**Comment by shawngiese** [comment]
Update your Flash plugin from the control panel. Then it will load.

**Comment by agologan** [comment]
This issue is way out of dated and it references a similar topic as #52 

If users still want to do this, the official ustream.tv website doesn't seem to support autoplay anymore but you can load up some 3rd party YouTube streams instead:
https://www.youtube.com/embed/XBPjVzSoepo?rel=0&autoplay=1;mute=1;controls=0
https://www.youtube.com/embed/EEIk7gwjgIM?rel=0&autoplay=1;mute=1;controls=0
