### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by bullox** [liquidx/webviewscreensaver#6]
Hey Alastair, would love to be able to use this on Mavericks - any chance of an update?

**Comment by PatTheMav** [comment]
If the execution is blocked because the screensaver is "unsigned", you can just right-click the .screensaver file and select "open". The dialog will allow you to install the screensaver even though it's not signed.

@liquidx Any chance you could update the packaged build? The available one is from 2010, your most recent changes are from 2012, so it would be nice having those changes available in a public release.

**Comment by liquidx** [comment]
I'll look in to updating and signing it properly. I've been putting it off
for too long

**Comment by calissendorff** [comment]
building the latest version works well

**Comment by liquidx** [comment]
The newest 2.0 release is now correctly signed and working on 10.9 and 10.10.

https://github.com/liquidx/webviewscreensaver/releases
