### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by JO77-Tech** [liquidx/webviewscreensaver#60]
Could we make a choice to make our YouTube full screen? really hope that would happen.

**Comment by nicolasrodi** [comment]
For the URL:
Go on your Youtube stream
Right-Click, Copy embed code
When you'll paste it, only take the URL
<iframe width="1031" height="580" src="YourURL" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

And add this at the end of the url

« ?rel=0&amp;autoplay=1;fs=0;autohide=0;hd=0;mute=1 »

If you want sound, you can enter mute=0 instead of mute=1

**Comment by agologan** [comment]
Thank you @nicolasrodi for the step by step guide.

Please refer to YouTube's [Embed videos & playlists](https://support.google.com/youtube/answer/171780) guidelines for future updates.
