### ISSUE TITLE
Nightscout not loading any more on Webviewscreensaver

### ISSUE THREAD

**Issue by Roza2011** [liquidx/webviewscreensaver#62]
After running Webviewscreensaver on my Mac OS 10.12.6 without a problem for a long time I am now having an issue. The Nightscout page can not be loaded when selected as screensaver. It shows the Nightscout loading page with message "connecting to server" and it freezes there.Previously that was not the case. I have tried uninstalling the app and clearing the cache from Safari and Chrome. I have also searched ~/Library/Caches and delated all found related files however I am still missing something since after reinstalling, the app picks up the Nightscout page address on its own. This mean I did not successfully cleared all of the cache. Any help how to clear the cache?

**Comment by agologan** [comment]
Our new version includes an option to clear the webView cache and associated data: https://github.com/liquidx/webviewscreensaver/releases/tag/v2.1
Also, configuration is tied to the macOS `defaults` system and is not cleared on reinstall.

**Comment by Roza2011** [comment]
> Our new version includes an option to clear the webView cache and associated data: https://github.com/liquidx/webviewscreensaver/releases/tag/v2.1
> Also, configuration is tied to the macOS `defaults` system and is not cleared on reinstall.

Many thanks for your reply. I have tried v2.1 and have clicked button to clear the cache and history however still my problem is there. Nothing has apparently changed with my issue with new version. If I set my nightscout page clock view as a screensaver then webviewscreensaver displays it without any problem, however if I set my default nightscout home page as a screen saver  then It shows the Nightscout loading page with message "connecting to server" and it freezes there. 
How to reset or clear configuration tied to the macOS defaults system? I hope I am making sense with my problem and the question. Thank you for your help.

**Comment by agologan** [comment]
_Please do not duplicate your reply across several issues. One time is enough._

You do **not** need to clear the `defaults` configuration, that just holds the list of addresses configured, nothing else.

First step in figuring out this issue is making sure you can load your server in Safari.
If that works, then please be aware that application data(e.g. cookies) between Safari and the screensaver are not shared so if you require extra configuration via use input it will not work atm.
A good test to ensure it will work in the screensaver is to load your URL in **incognito** in Safari.
If that works without further user input then it should be a safe bet it also works as a screensaver.

Normally we don't debug individual applications since the screensaver just wraps the standard WebKit browser so it's up to the users to make sure their individual apps work.
That being said if you could provide a demo environment I'll spend a few minutes looking at the issue you're encountering.
_Feel free to email me, if it's a private deployment that you don't want to share publicly._

**Comment by Roza2011** [comment]
Dear Alexandru many thanks for your message. Apologies for duplicating my
query. I have tested my URL incognito in Safari only to find out that
Safari is having the same issue as screensaver. The only difference in
Safari is that it loads the complete Nightscout page briefly and then
reload starts again. Chrome is loading my URL without any issue.
Unfortunately I am not sure what I have to do to provide a demo
environment. I do not expect you to guide me through and would like you to
know how much I appreciate your time and help in this matter so far. Best
regards.

pon, 26. lis 2020. u 18:08 Alexandru Gologan <notifications@github.com>
napisao je:

**Comment by agologan** [comment]
Recommend enabling Safari Developer options, by going to Settings > Advanced > Show Develop menu in menu bar.
Afterwards opening up the Inspector via menu Develop > Show Inspector or Cmd + Shift + I
And looking at the JS console, which may provide some additional information on why Nightscout is failing.

**Comment by agologan** [comment]
Closing issue as this is not a screensaver problem.
