### ISSUE TITLE
.m3u8 links no longer working (Sonoma)

### ISSUE THREAD

**Issue by benwingrove** [liquidx/webviewscreensaver#78]
I use WebViewScreenSaver to display a live web cam feed using the .m3u8 format, (https://b10.hdrelay.com/camera/edd38a74-f4cf-4014-8a63-f3c080182b8d/relay/playlist.m3u8) since upgrading to MacOs 14.2.1 it no longer auto loads the feed! the link I use still works in Safari. any workarounds that can be suggested?

**Comment by pluto202** [comment]
Seems I’m facing a comparable issue. I’m presenting my Smarthome Dashboard as a screen saver view. Since updating my Mac to the latest version the information (e.g. power consumption and PV production) are frozen. Dashboard is  based on iobroker. Any ideas to get it going again? Thanks a lot, Andreas

**Comment by agologan** [comment]
Seems to be the same issue reported here: #75 
Now fixed with `v2.3`.
